
version: "3.1"

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - node
  
  node:
    container_name: nodeserver
    image: nodeserver
    build:
      context: .
      dockerfile: .docker/nodeserver.dockerfile
    ports:
      - "4300:4300"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge